---

content_importer_delegate_to: localhost

content_importer_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/content_importer', true) }}"

content_importer_remote_tmp_directory: /root/.ansible/content_importer

content_importer_requirements:
  - gzip

...
