---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: instance
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_TIME
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      fact_caching: "jsonfile"
      fact_caching_timeout: 8640
      fact_caching_connection: "/tmp/ansible_facts"

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
