---

- name: create applications directory
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_config_base_directory }}/{{ item }}"
    owner: "{{ prometheus_config_owner }}"
    group: "{{ prometheus_config_group }}"
    mode: 0775
  loop:
    "{{ prometheus_config_allowlist | bodsch.coremedia.coremedia_applications }}"

- name: create jmx_prometheus.yml configuration
  ansible.builtin.template:
    src: jmx_prometheus.yml.j2
    dest: "{{ prometheus_config_base_directory }}/{{ item }}/jmx_prometheus.yml"
    mode: 0644
    owner: "{{ prometheus_config_owner }}"
    group: "{{ prometheus_config_group }}"
  loop:
    "{{ prometheus_config_allowlist | bodsch.coremedia.coremedia_applications }}"

...
