---
- name: converge
  hosts: all
  any_errors_fatal: false

  environment:
    NETRC: ''
    # https://github.com/ansible/ansible/issues/77133
    # https://github.com/ansible/ansible/pull/76542
    # LANGUAGE: en_UK.utf8

  roles:
    - role: bodsch.coremedia.management
      vars:
        coremedia_management_feeder:
          name: "caefeeder-live"
          command: "reset"
          extra_hosts:
            "registry.cm.local": "192.168.124.10"
