---

- name: approve themes
  bodsch.coremedia.themes_importer:
    state: approve
    management_container_image: "{{ management_container.name }}"
    content_server_ior: "{{ themes_importer.content_server_ior }}"
    coremedia_admin: "{{ themes_importer.admin_user }}"
  register: _publish

- name: output from approve themes
  debug:
    msg: "{{ _publish }}"

...
