---

- name: create temporary directory on ansible controller
  become: false
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    state: directory
    path: "{{ themes_importer_tmp_directory }}"
    mode: 0750

- name: create temporary directory on destination instance
  ansible.builtin.file:
    state: directory
    path: "{{ themes_importer_paths.tmp_remote }}/archive"
    owner: "{{ themes_importer_owner }}"
    group: "{{ themes_importer_group }}"
    mode: 0750

- name: download theme artefacts from jenkins to ansible controller
  become: false
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ themes_importer_source.archive }}"
    url_username: "{{ themes_importer_source.username }}"
    url_password: "{{ themes_importer_source.password }}"
    validate_certs: "{{ themes_importer_source.validate_certs | default(omit) }}"
    force_basic_auth: true
    dest: "{{ themes_importer_tmp_directory }}/coremedia-themes-archive.zip"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: transfer theme artefacts from ansible controller to {{ ansible_hostname }}
  ansible.builtin.copy:
    src: "{{ themes_importer_tmp_directory }}/coremedia-themes-archive.zip"
    dest: "{{ themes_importer_paths.tmp_remote }}/archive/"
    mode: 0644

- name: fix directory rights for {{ themes_importer_paths.tmp_remote }}/archive
  ansible.builtin.file:
    path: "{{ themes_importer_paths.tmp_remote }}/archive"
    state: directory
    owner: "{{ themes_importer_owner }}"
    group: "{{ themes_importer_group }}"
    recurse: true

...
