---

- name: merge configuration between defaults and custom
  ansible.builtin.set_fact:
    themes_importer_source: "{{ themes_importer_defaults_source | combine(themes_importer_source, recursive=True) }}"

- name: validate themes_importer_source
  fail:
    msg: "your download definition is not valid!\n
         The following parameters are required:\n
         - archive   : the url to the jenkins download archive\n
         - username  : the login username for jenkins\n
         - password  : the login password for jenkins"
  when:
    - (not themes_importer_source.archive is defined or
           themes_importer_source.archive | string | length == 0) or
      (not themes_importer_source.username is defined or
           themes_importer_source.username | string | length == 0) or
      (not themes_importer_source.password is defined or
           themes_importer_source.password | string | length == 0)

- name: verify container
  bodsch.coremedia.management_tools:
    management_container_image: "{{ management_container.name | default('')  }}"
  register: _container

- name: management container
  when:
    - _container is defined
    - not _container.container_image is defined or _container.container_image | string | length == 0
  block:
    - name: management container '{{ management_container.name }}'
      debug:
        msg: "{{ _container }}"
      when:
        - _container is defined

    - name: pull management container from container registry
      community.general.docker_image:
        name: "{{ management_container.name }}"
        source: pull
        force_tag: true
        force_source: true
      register: _container_images_information_pulled
      ignore_errors: false
      tags:
        - container_pull

    - name: pull container
      debug:
        msg: "{{ _container_images_information_pulled.actions | default('') }}"

- name: merge configuration between defaults and custom
  ansible.builtin.set_fact:
    themes_importer: "{{ themes_importer_defaults | combine(themes_importer, recursive=True) }}"

...
