---

galaxy_info:
  role_name: licensess
  namespace: bodsch

  author: Bodo Schulz <bodo@boone-schulz.de>
  description: A role for deploying CoreMedia License Files

  license: Apache

  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - coremedia

dependencies: []
