---

- name: prepare
  ansible.builtin.import_tasks: prepare.yml

- name: caefeeder
  import_tasks: caefeeder.yml
  when:
    - caefeeder is defined
    - caefeeder | count > 0
    - caefeeder.name is defined
    - caefeeder.name | string | length > 0
    - caefeeder.name in ['caefeeder-live', 'caefeeder-preview']

...
