---

galaxy_info:
  role_name: coremedia_management
  namespace: bodsch

  author: Bodo Schulz <bodo@boone-schulz.de>
  description: A role for handle CoreMedias management-tools Container

  company: "Tallence AG"
  license: "own"

  min_ansible_version: "2.10"

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - coremedia

dependencies: []
